### ISSUE TITLE
It's easy to create duplicate copies of manuals

### ISSUE THREAD

**Issue by alexmuller** [alphagov/manuals-publisher#621] opened 2015-12-23 11:26 UTC
Steps to reproduce:
- Create a new manual and fill in the title, summary and body
- Click 'Save as draft' really fast lots of times

Expected results:
- There should only be one copy of the new manual in the manuals list

Actual results:
- There are lots of copies of the same manual in the manuals list

**Comment by h-lame** [comment] 2017-02-16 14:53
I think this was fixed by #762, so I'm closing this.

We do have a different duplication problem written up as https://trello.com/c/R3kQxY9Z/81-duplication-bug-in-manuals but it's not caused by the same problem as described here.

**Closed by h-lame** 2017-02-16 14:53 UTC
