### ISSUE TITLE
Tests fail with new bundler on CI

### ISSUE THREAD

**Issue by tijmenb** [alphagov/manuals-publisher#816] opened 2017-03-06 16:27 UTC
We're seeing these errors on master:

```
LoadError: cannot load such file -- active_model/translation
/var/lib/jenkins/bundles/manuals-publisher/deployed-to-production/ruby/2.2.0/gems/activemodel-3.2.22.3/lib/active_model/validations.rb:49:in `block in <module:Validations>'
/var/lib/jenkins/bundles/manuals-publisher/deployed-to-production/ruby/2.2.0/gems/activesupport-3.2.22.3/lib/active_support/concern.rb:121:in `class_eval'
/var/lib/jenkins/bundles/manuals-publisher/deployed-to-production/ruby/2.2.0/gems/activesupport-3.2.22.3/lib/active_support/concern.rb:121:in `append_features'
```

This has also been noted in https://github.com/alphagov/manuals-publisher/commit/0a674b5352d7a9de7df04aefd449535abf65a210.

**Comment by tijmenb** [comment] 2017-03-06 16:30
https://github.com/alphagov/govuk-content-schemas/pull/555 should be reverted after this is fixed.

**Comment by h-lame** [comment] 2017-03-06 17:55
Don't really know what the cause is but it works with bundler 1.12.6 (latest 1.12 series) and fails with bundler 1.13.0 (first in bundler 1.13 series).  This might help with tracking it down - although nothing obvious jumps out at me from the bundler changelog.

**Comment by h-lame** [comment] 2017-03-06 17:59
You can trigger it by running `bundle exec rake spec:javascript` or `bundle exec rake cucumber`.  `bundle exec rake spec` works, `bundle exec rake test` runs the specs and then fails when it tries to run the cucumber features.  The problem may lurk in the cucumber and jasmine rakefiles and how they require things.

**Comment by floehopper** [comment] 2017-03-07 09:02
I assume this has been triggered by the upgrade of Bundler for Ruby v2.2.4 from v1.10.6 to v1.14.5 in alphagov/govuk-puppet@857083c4431ced07b910578d50a9450c39fbea95.

I think the problem is to do with the `mongoid_rails_migrations` gem; more specifically because the gem calls `Bundle.require` when it is required by Bundler - see [this line](https://github.com/adacosta/mongoid_rails_migrations/blob/460a92dcf6fcca8b0cf82f6bd6457e4a4fe31442/lib/mongoid_rails_migrations.rb#L3).

It looks as if someone attempted a proper fix for this in adacosta/mongoid_rails_migrations#13 6 years ago, but the author didn't seem to understand the problem. I suggest we either find a fork where this has been fixed or implement a new version of that PR in our own fork.

**Comment by h-lame** [comment] 2017-03-07 09:56
The problem seems to be: https://github.com/bundler/bundler/issues/5500. Both cucumber and jasmine-rails fork the ruby process when running their rake tasks and these "nested" bundle exec calls seem to mess up the bundle environment.  Note that jasmine-rails only if the RAILS_ENV isn't already test so we can avoid the problem by running `RAILS_ENV=test bundle exec rake spec:javascript`.  We can avoid the problem with cucumber too by changing `t.fork = true` to `t.fork = false` in [`lib/tasks/cucumber.rake`](lib/tasks/cucumber.rake) and also running with an explicit `RAILS_ENV` (e.g. `RAILS_ENV=test bundle exec rake cucumber`).  There's a fix in https://github.com/bundler/bundler/pull/5504 that asks bundler not to reset (this change introduced in bundler 1.13.x) and doing the same change locally fixes the problem without needing to change our rake tasks, or be explicit about RAILS_ENV when running the rake tasks.

**Comment by floehopper** [comment] 2017-03-07 11:36
@h-lame: Do the changes you recommend mean that we end up with "non-standard" rake tasks? Would it not be better to fix the problem in the `mongoid_rails_migration` gem?

**Comment by h-lame** [comment] 2017-03-07 11:39
I don't think we should "fix" the rake tasks because we can't really; they need to be run with different arguments.  I'm not entirely sure that using a fixed `mongoid_rails_migration` gem solves the problem, but I could be wrong.  I think we need to have a bigger debate about rolling back the bundler update until https://github.com/bundler/bundler/pull/5504 is merged and released.

**Comment by h-lame** [comment] 2017-03-07 11:40
Ofc, using a fixed `mongoid_rails_migration` gem might mean we need to upgrade to a newer `mongoid` which means a newer `rails`.  Not trivial, but also not useless.

**Comment by floehopper** [comment] 2017-03-07 15:08
I've just pushed up a bodgy fix: #822.

**Comment by floehopper** [comment] 2017-03-08 15:18
In the short term, we're not planning on trying to improve this fix unless we run into specific problems with it. I'm going to leave this issue open for the moment as a reminder that in the longer run it would be good to come up with a better fix.

**Comment by chrisroos** [comment] 2017-03-09 15:45
> I'm going to leave this issue open for the moment as a reminder that in the longer run it would be good to come up with a better fix.

@floehopper: How about opening a new issue to capture any improvement given that this issue has been fixed?

**Comment by floehopper** [comment] 2017-03-09 15:53
@chrisroos: Sure. Be my guest.

**Comment by chrisroos** [comment] 2017-03-15 12:42
I've created issue #874 to remind us that we might want to improve the fix in mongoid_rails_migrations.

I can now close this issue.

**Closed by chrisroos** 2017-03-15 12:42 UTC
