### ISSUE TITLE
Unexpected updates for The Highway Code on 1 Mar 2017

### ISSUE THREAD

**Issue by brenetic** [alphagov/manuals-publisher#861] opened 2017-03-13 13:10 UTC
This problem was originally reported in [Zendesk ticket 1901209][zendesk-1901209] on 1 Mar 2017.

There are unexpected [updates listed for The Highway Code][highway-code-updates] against 1 March 2017.

We expect to see "Annex 5 Penalties" with a single change described as "Updated the penalty table to increase penalty points for using a hand-held mobile phone when driving from 3 to 6.".

We're also seeing:

* Road users requiring extra care (204 to 225)
  * Updated Rule 209 to add an image of the school bus road sign.
* Signals to other road users
  * New section added.
* Signals by authorised persons
  * New section added.
* Road markings
  * New section added.
* Vehicle markings
  * New section added.
* Annex 8. Safety code for new drivers
  * Updated the Pass Plus email address to passplus@dvsa.gov.uk

For all the updates on 1 March 2017 we're seeing two identical change notes, one with a timestamp of 2017-03-01T09:49:18Z and the other with a timestamp of 2017-03-01T11:03:18Z.

[highway-code-updates]: https://www.gov.uk/guidance/the-highway-code/updates
[zendesk-1901209]: https://govuk.zendesk.com/agent/tickets/1901209

**Comment by chrisroos** [comment] 2017-04-04 15:50
@brenetic: Do you know what's happening with this issue? I can see that the problem is also mentioned in [this Trello card](https://trello.com/c/JGuGBZD2/118-fix-update-date-in-manuals-publisher) but that the card's been archived today. Do you know whether I can close this issue?

**Comment by chrisroos** [comment] 2017-04-04 15:55
I've added a [comment to the Trello card to ask Liz L if this is being handled elsewhere](https://trello.com/c/JGuGBZD2/118-fix-update-date-in-manuals-publisher#comment-58e3c1b93e73079175ebc081).

**Comment by brenetic** [comment] 2017-04-04 16:38
@chrisroos I'm afraid I have not been keeping track of it. I had thought that Survey and Support were doing it? I can ask Liz L tomorrow

**Comment by chrisroos** [comment] 2017-04-10 13:17
I've spoken to Antonia (whose team is looking after manuals-publisher) and agreed to investigate this issue.

**Comment by chrisroos** [comment] 2017-04-10 15:26
I've updated the description of the issue now that I understand more about the problem.

**Comment by chrisroos** [comment] 2017-04-10 15:41
There were a number of exceptions in errbit around the time the issue was raised in Zendesk. These exceptions contain the Manual ID of The Highway Code (bbf6c11a-7dc6-4fe6-8dd8-68c09bdbe562) so I suspect they might be related:

* [GdsApi::HTTPServerError: URL: https://publishing-api.publishing.service.gov.uk/v2/links/bbf6c11a-7dc6-4fe6-8dd8-68c09bdbe562](https://errbit.publishing.service.gov.uk/apps/57e3ddba6578636ac8300000/problems/58b67fc765786368ed3d1400)

* [GdsApi::TimedOutException](https://errbit.publishing.service.gov.uk/apps/57e3ddba6578636ac8300000/problems/5875f96a6578636265fe0800)

* [ArgumentError: invalid date](https://errbit.publishing.service.gov.uk/apps/57e3ddba6578636ac8300000/problems/58b6939465786368edf62300)

**Comment by chrisroos** [comment] 2017-04-10 15:46
I can see the duplicate entries in details > change_notes information in the [Content API for The Highway Code](https://www.gov.uk/api/content/guidance/the-highway-code).

**Comment by chrisroos** [comment] 2017-04-10 15:50
I can also see these duplicate changes in the `PublicationLog`s in my local copy of the data:

```
>> PublicationLog.change_notes_for('guidance/the-highway-code').each { |cn| p cn }; nil

#<PublicationLog _id: 58b6991eed915d158f000009, created_at: 2017-03-01 09:49:18 UTC, updated_at: 2017-03-01 09:49:18 UTC, slug: "guidance/the-highway-code/annex-8-safety-code-for-new-drivers", title: "Annex 8. Safety code for new drivers", change_note: "Updated the Pass Plus email address to passplus@dvsa.gov.uk", version_number: 5>

#<PublicationLog _id: 58b6aa76ed915d158f000010, created_at: 2017-03-01 11:03:18 UTC, updated_at: 2017-03-01 11:03:18 UTC, slug: "guidance/the-highway-code/annex-8-safety-code-for-new-drivers", title: "Annex 8. Safety code for new drivers", change_note: "Updated the Pass Plus email address to passplus@dvsa.gov.uk", version_number: 6>
```

**Comment by chrisroos** [comment] 2017-04-13 09:22
@chrislo and I believe we understand how this has happened and that it's been caused by a bug in the code. We've opened issue #970 to describe this bug which should help us prevent these sort of problems in future.

**Comment by chrisroos** [comment] 2017-04-13 10:55
I think we now have a fairly good idea about the cause of these duplicate updates.

This all happened on 1 Mar 2017. I'm not entirely confident about the times but am leaving them in case they're useful in future.

* 07:47
  * SectionEdition 58b67caded915d1533000010 "Annex 5. Penalties" is updated with the new information
* 09:25
  * Originally published at date is set to 01 Oct 2015
  * This creates duplicate SectionEditions (see bug #970)
* 09:49
  * Manual is published
  * This creates unexpected PublicationLog entries based on the duplicate SectionEditions created above
  * It's possible there were API timeouts at this time which made it hard to work out what was happening
* 11:02
  * Originally published at date is set to 01 Oct 2015
  * This creates duplicate SectionEditions (see bug #970)
* 11:03
  * Manual is published
  * This creates duplicate PublicationLog entries of those created at 09:49

**Comment by chrisroos** [comment] 2017-04-13 10:59
We plan to fix the problem by:

1. Adding a migration to "reset" the `minor_change` and `change_note` attributes of the `SectionEdition` records created as part of updating the originally published at timestamp on 1 Mar 2017.

2. Using a modified version of the `rebuild_major_publication_logs_for_manuals` script to recreate the `PublicationLog`s for The Highway Code.

3. Using a modified version of the `republish_manuals` script to re-publish The Highway Code to the Publishing API.

4. Add information to the README to help people should this problem happen in future (i.e. before bug #970 is fixed).

**Comment by chrisroos** [comment] 2017-04-13 13:47
PR #973 contains a migration to fix the data as described in step 1 above.

PR #971 converts the `rebuild_major_publication_logs_for_manuals` script to a Rake task and adds the ability to rebuild the logs for a single manual. This helps with step 2 in the list above.

PR #972 has converted the `republish_manuals` script to a Rake task and added the ability to republish a single manual. This helps with step 3 in the list above.

We've deployed and run the migration in integration and followed up by running the two Rake tasks mentioned. The combination appears to fix The Highway Code in integration. We aim to get this deployed to production next week.

**Comment by chrisroos** [comment] 2017-04-18 15:55
We've now deployed this fix to staging and production. The Highway Code updates are now showing a single entry for 1 Mar 2017 as expected.

![screenshot 2017-04-18 16 54 50](https://cloud.githubusercontent.com/assets/6556/25140322/cc49e180-2457-11e7-9415-75598b88be50.png)

**Comment by chrisroos** [comment] 2017-04-18 15:55
In case it's useful in future, this is the output of running the migration from PR #973 in production:

```
** [out :: server] ==  FixChangeNoteDataForTheHighwayCode: migrating =============================
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a9700001d, Road users requiring extra care (204 to 225) , 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d87000018, Road users requiring extra care (204 to 225) , 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a97000024, Signals to other road users, 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d8700001f, Signals to other road users, 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a97000025, Signals by authorised persons, 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d87000020, Signals by authorised persons, 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a97000027, Road markings, 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d87000022, Road markings, 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a97000028, Vehicle markings, 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d87000023, Vehicle markings, 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6939c40f0b64a9700002f, Annex 8. Safety code for new drivers, 2017-03-01 09:25:48 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d8700002b, Annex 8. Safety code for new drivers, 2017-03-01 11:02:33 UTC
** [out :: server] Updated SectionEdition with attributes: 58b6aa49e5274a5d87000028, Annex 5. Penalties, 2017-03-01 11:02:33 UTC
** [out :: server] ==  FixChangeNoteDataForTheHighwayCode: migrated (2.0192s) ====================
```

**Comment by chrisroos** [comment] 2017-04-18 15:56
I think this is finally fixed so I'm closing the issue.

**Closed by chrisroos** 2017-04-18 15:56 UTC
